export const OBSERVABLE_REGISTER = 'OBSERVABLE_REGISTER';
export const OBSERVABLE_REMOVE   = 'OBSERVABLE_REMOVE';
export const OBSERVABLE_UPDATE   = 'OBSERVABLE_UPDATE';
export const OBSERVABLE_START    = 'OBSERVABLE_START';
export const OBSERVABLE_STOP     = 'OBSERVABLE_STOP';